version: "3"
services:
  vehicleInventoryApp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../dist:/usr/src/vehicleInventoryApp # Mount the dist directory into the container
    restart: always
